services:
  - type: web
    name: navkankari
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NAVKANKARI_SECRET
        generateValue: true
